# Honor Pledge: I will neither give nor receive aid on this assessment.

import sys
sys.stdout.write('MAIL FROM: <jeffay @cs.unc.edu>\n')
sys.stdout.write('MAIL FROM: <jeffay@cs.unc.edu >\n')
sys.stdout.write('MAIL-FROM: <jeffay@cs.unc.edu>    \n')
sys.stdout.write('MAIL FROM:    < jeffay@cs.unc.edu>\n')
sys.stdout.write('MAIL    FROM: <jef fay@cs.unc.edu>\n')
sys.stdout.write('MAIL FROM:    <jeffay@ cs.un@c.edu>    \n')
sys.stdout.write('MAIL FROM<jeffay@ cs.un@c.edu>\n')
sys.stdout.write('MAIL FROM::<jeffay@cs.unc.edu>\n')
sys.stdout.write('MAiL FROM: <jeffay@cs>\n')
sys.stdout.write('MAIL FROm: <jeffay@unc.edu>\n')
sys.stdout.write('MAIL FROM: <jeffay@unc.edu    >\n')
sys.stdout.write('MAIL FROM: <jeffay@unc..edu>\n')
sys.stdout.write('MAIL FROM: <jeffay@@unc.edu>\n')
sys.stdout.write('MAIL FROM: <jeffay@unc.@edu>\n')
sys.stdout.write('MAIL FROM: <jeffay@1nc.edu>\n')
sys.stdout.write('MAIL FROM: <jeffay@unc.eduuuu333>@\n')
sys.stdout.write('MAIL FROM: <jeffay@unc.eduuuu333>@  \n')
sys.stdout.write("FROM:<jeffay@cs.unc.edu>\n")
sys.stdout.write("MAIL:<jeffay@cs.unc.edu>\n")
sys.stdout.write("MAIL FROM:jeffay@cs.unc.edu\n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu!>\n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu> send\n")
sys.stdout.write('MAILFROM:<jeffay@cs.unc.edu>\n')
sys.stdout.write("MAIL <jeffay@cs.unc.edu>\n")
sys.stdout.write("MAIL FROM: < jeffay@cs.unc.edu >\n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu>")
sys.stdout.write("MAIL FROM: <jeffay@cs.unc.edu>\n")
sys.stdout.write("MAIL FROM: <jeffay@cs.unc.edu>        r\n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu> \n  MAIL FROM:<jeffay@cs.unc.edu> \n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu>             \nMAIL FROM:< jeffay@cs.unc.edu> \n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu>\nMAIL FROM:<jeffay@cs.3nc.edu> \n")
sys.stdout.write("MAIL FROM:<jeffay@cs.unc.edu>\nMAIL    FROM:   <jeffay@cs.unc.edu> \nMAIL FROM: <jeffay@c4.unc.edu > \n")

#sys.stdout.write('MAIL FROM: <jeffay@unc.edu>\n     ')
#sys.stdout.write('MAIL FROM: <jeffay@unc.edu>        ')

